#!/bin/bash
# Generated by Cerberus

set -e

# Validate bot policy
if [[ -f /app/botPolicy.json ]]; then
    echo "Using custom bot policy"
else
    echo "Warning: No bot policy found"
fi

# Environment setup
export BIND="${BIND:-:8080}"
export DIFFICULTY="${DIFFICULTY:-5}"
export TARGET="${TARGET:-http://proxy-2:80}"
export METRICS_BIND="${METRICS_BIND:-:9090}"
export SERVE_ROBOTS_TXT="${SERVE_ROBOTS_TXT:-true}"

# Custom initialization
if [[ -d /docker-entrypoint-init.d ]]; then
    for script in /docker-entrypoint-init.d/*.sh; do
        if [[ -x "$script" ]]; then
            echo "Running $script..."
            "$script"
        fi
    done
fi

# Start Anubis
exec "$@"
