#!/bin/bash

# Test script for Dockerfile Generator

set -euo pipefail

# Setup paths
SCRIPT_DIR="/mnt/e/codeing/shellscript/cerberus"
export SCRIPT_DIR
export BUILT_DIR="${SCRIPT_DIR}/tests/tmp"

echo "Testing Dockerfile Generator..."
echo "=============================="

# Load libraries
source "${SCRIPT_DIR}/lib/core/utils.sh"
source "${SCRIPT_DIR}/lib/core/config-simple.sh"
source "${SCRIPT_DIR}/lib/generators/dockerfiles.sh"

# Create test configuration
cat > "${SCRIPT_DIR}/tests/tmp/dockerfile-test.toml" << 'EOF'
[project]
name = "test-project"

[[proxies]]
name = "nginx-proxy"
type = "nginx"
external_port = 8080
internal_port = 80

[[proxies]]
name = "caddy-proxy"
type = "caddy"
external_port = 8081
internal_port = 80

[[proxies]]
name = "haproxy-proxy"
type = "haproxy"
external_port = 8082
internal_port = 80

[[proxies]]
name = "traefik-proxy"
type = "traefik"
external_port = 8083
internal_port = 80

[anubis]
enabled = true
bind = ":8080"
difficulty = 5
target = "http://proxy-2:80"
EOF

echo "1. Loading configuration..."
config_load "${SCRIPT_DIR}/tests/tmp/dockerfile-test.toml"

echo "2. Generating Dockerfiles..."
rm -rf "${BUILT_DIR}/dockerfiles"
if generate_dockerfiles; then
    echo "✓ Dockerfiles generated successfully"
else
    echo "✗ Dockerfile generation failed"
    exit 1
fi

echo "3. Checking generated files..."
# Check each proxy type
for proxy in nginx-proxy caddy-proxy haproxy-proxy traefik-proxy; do
    if [[ -f "${BUILT_DIR}/dockerfiles/${proxy}/Dockerfile" ]]; then
        echo "✓ Dockerfile created for $proxy"
        
        # Check entrypoint
        if [[ -f "${BUILT_DIR}/dockerfiles/${proxy}/entrypoint.sh" ]]; then
            echo "✓ entrypoint.sh created for $proxy"
        else
            echo "✗ entrypoint.sh missing for $proxy"
        fi
        
        # Check content
        if grep -q "Generated by Cerberus" "${BUILT_DIR}/dockerfiles/${proxy}/Dockerfile"; then
            echo "✓ Dockerfile contains generator marker"
        fi
    else
        echo "✗ Dockerfile missing for $proxy"
    fi
done

# Check Anubis
if [[ -f "${BUILT_DIR}/dockerfiles/anubis/Dockerfile" ]]; then
    echo "✓ Dockerfile created for Anubis"
fi

echo "4. Generating build script..."
generate_build_script
if [[ -f "${BUILT_DIR}/dockerfiles/build-all.sh" ]]; then
    echo "✓ Build script generated"
    if [[ -x "${BUILT_DIR}/dockerfiles/build-all.sh" ]]; then
        echo "✓ Build script is executable"
    fi
fi

echo "5. Validating Dockerfiles..."
if validate_dockerfiles; then
    echo "✓ All Dockerfiles validated successfully"
else
    echo "✗ Dockerfile validation failed"
fi

echo "6. Sample Dockerfile content..."
echo "--- nginx-proxy/Dockerfile (first 10 lines) ---"
head -10 "${BUILT_DIR}/dockerfiles/nginx-proxy/Dockerfile"

echo
echo "All tests completed!"