#!/bin/bash
# Generated by Cerberus

set -e

# Environment variable substitution in config files
if [[ -n "${UPSTREAM}" ]]; then
    find /etc/nginx/conf.d -name "*.conf" -exec sed -i "s|http://backend|${UPSTREAM}|g" {} \;
fi

# Custom initialization
if [[ -f /docker-entrypoint-init.d/*.sh ]]; then
    for script in /docker-entrypoint-init.d/*.sh; do
        if [[ -x "$script" ]]; then
            echo "Running $script..."
            "$script"
        fi
    done
fi

# Start nginx
exec "$@"
