#!/bin/bash
# Generated by Cerberus

set -e

# Environment variable substitution in Caddyfile
if [[ -n "${UPSTREAM}" ]]; then
    sed -i "s|http://backend|${UPSTREAM}|g" /etc/caddy/Caddyfile
fi

# Custom initialization
if [[ -d /docker-entrypoint-init.d ]]; then
    for script in /docker-entrypoint-init.d/*.sh; do
        if [[ -x "$script" ]]; then
            echo "Running $script..."
            "$script"
        fi
    done
fi

# Start Caddy
exec "$@"
