#!/bin/bash
# Generated by Cerberus

set -e

# Validate HAProxy configuration
haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg

# Environment variable substitution
if [[ -n "${UPSTREAM}" ]]; then
    sed -i "s|server backend1.*|server backend1 ${UPSTREAM} check|g" /usr/local/etc/haproxy/haproxy.cfg
fi

# Custom initialization
if [[ -d /docker-entrypoint-init.d ]]; then
    for script in /docker-entrypoint-init.d/*.sh; do
        if [[ -x "$script" ]]; then
            echo "Running $script..."
            "$script"
        fi
    done
fi

# Start HAProxy
exec "$@"
