#!/bin/bash
# Generated by Cerberus

set -e

# Environment variable substitution
if [[ -n "${UPSTREAM}" ]]; then
    find /etc/traefik/dynamic -name "*.yml" -o -name "*.yaml" | \
        xargs sed -i "s|http://backend|${UPSTREAM}|g"
fi

# Custom initialization
if [[ -d /docker-entrypoint-init.d ]]; then
    for script in /docker-entrypoint-init.d/*.sh; do
        if [[ -x "$script" ]]; then
            echo "Running $script..."
            "$script"
        fi
    done
fi

# Start Traefik
exec "$@"
