#!/bin/bash
# Generated by Cerberus
# Build all Docker images

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_NAME="${PROJECT_NAME:-cerberus}"

echo "Building Docker images for $PROJECT_NAME..."

# Build each proxy image
for proxy_dir in "$SCRIPT_DIR"/*/; do
    if [[ -f "$proxy_dir/Dockerfile" ]]; then
        proxy_name=$(basename "$proxy_dir")
        echo "Building $proxy_name..."
        
        # Copy config files if they exist
        config_dir="../../proxy-configs/$proxy_name"
        if [[ -d "$config_dir" ]]; then
            cp -r "$config_dir"/* "$proxy_dir/" 2>/dev/null || true
        fi
        
        # Build image
        docker build -t "$PROJECT_NAME/$proxy_name:latest" "$proxy_dir"
        
        echo "✓ Built $PROJECT_NAME/$proxy_name:latest"
    fi
done

echo "All images built successfully!"
