# TLS/CA enabled configuration example
# Copy this to config.toml and modify as needed

[global]
auto_https = true   # Enable HTTPS
admin = false

# TLS/CA Configuration
[tls]
enabled = true

[tls.ca]
# Internal CA configuration
enabled = true
root_cert = "/etc/ssl/ca.crt"
root_key = "/etc/ssl/ca.key"

# Custom certificate paths
[[tls.certificates]]
domain = "*.ruruke.moe"
cert_file = "/etc/ssl/wildcard.crt"
key_file = "/etc/ssl/wildcard.key"

# Update ports to 443 for HTTPS
[proxy_layer1]
listen_port = 443  # Change from 80 to 443
default_upstream = "http://anubis:8080"

[[proxy_layer1.direct_routes]]
domain = "media.ruruke.moe"
upstream = "http://proxy-2:443"  # Update to 443

[[proxy_layer1.direct_routes]]
domain = "summaly.ruruke.moe"
upstream = "http://proxy-2:443"

[[proxy_layer1.direct_routes]]
domain = "storage.ruruke.moe"
upstream = "http://proxy-2:443"

[proxy_layer1.misskey_routes]
domain = "mi.ruruke.moe"
bypass_paths = [
    "/streaming*",
    "/inbox*",
    "/outbox*",
    "/api*",
    "/.well-known*"
]
bypass_upstream = "http://proxy-2:443"
default_upstream = "http://anubis:8080"

[proxy_layer2]
listen_port = 443  # Change from 80 to 443

[[proxy_layer2.services]]
domain = "mi.ruruke.moe"
upstream = "http://100.103.133.21:3000"
max_body_size = "100MB"
websocket = true
access_log = "/var/log/caddy/misskey_access.log"

[[proxy_layer2.services]]
domain = "media.ruruke.moe"
upstream = "http://100.97.11.65:12766"
access_log = "/var/log/caddy/media_proxy_access.log"

[[proxy_layer2.services]]
domain = "storage.ruruke.moe"
upstream = "https://s3.ap-northeast-2-ntt.wasabisys.com/storage.ruruke.moe/"
max_body_size = "1000MB"
access_log = "/var/log/caddy/storage_access.log"
compress = true

[proxy_layer2.services.headers.request]
Host = "s3.us-east-2.wasabisys.com"
X-Forwarded-Proto = "https"
Proxy = ""

[proxy_layer2.services.headers.response]
Cache-Control = "public, max-age=2592000"
Pragma = "public"

[[proxy_layer2.services]]
domain = "summaly.ruruke.moe"
upstream = "http://100.114.43.64:3030"
access_log = "/var/log/caddy/summaly_access.log"

[[proxy_layer2.services]]
domain = "ruru.my"
upstream = "http://100.114.43.64:8080"
access_log = "/var/log/caddy/homepage_access.log"

[logging]
level = "INFO"
format = "json"
output = "/var/log/caddy/caddy.log"